# Download BBBC004
name: viz_workflow_BBBC008
steps:
    - bbbcdownload:
        plugin:
            name: "BbbcDownload"
            manifest: "https://raw.githubusercontent.com/saketprem/polus-plugins/bbbc_download/utils/bbbc-download-plugin/plugin.json"
        params:
            name: "BBBC008"
            outDir:
                type: Path
                path: InpDirFileRenaming
